# Generated by Django 6.0.3 on 2026-05-01 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
